### ISSUE TITLE
eddyfit2d

### ISSUE THREAD

**Issue by nbronikowski** [jonathanlilly/jLab#15]
Hi there, it seems eddyfit2d is missing a function definition "simpleddy" its trying to call? 
Not sure how it is supposed to work.

thanks so much,

Nicolai

**Comment by jonathanlilly** [comment]
Hi Nicolai, 

Thanks for pointing out the missing function; here it is.  I'll make sure to include it in the next release which should be happening shortly.

[simpleddy.m.zip](https://github.com/jonathanlilly/jLab/files/5652718/simpleddy.m.zip)

**Comment by nbronikowski** [comment]
Hi Jonathan,

Thank you so much for sending the file. Great toolbox!!

Cheers,
Nicolai
