### ISSUE TITLE
mspec returns ZERO spp, snn

### ISSUE THREAD

**Issue by hongandyan** [jonathanlilly/jLab#16]
I'm trying to use mspec
as
[f,spp,snn]=mspec(1,cv,[]);
but the returned values are
f=0,
spp and snn are all zeros.
My raw data is here
https://www.dropbox.com/s/qj0zrrmw8usl88t/PaPa2.mat?dl=0
where 
cv = UU_obs + i*VV_obs;
cv=cv-mean(cv);

Where could be wrong?
thanks

**Comment by jonathanlilly** [comment]
The two most likely causes are (i) you put your data in as a row vector (it
must be a column) or (ii) it contains a non-finite value.  If neither of
those work, let me know and I'll check out your data.
Jonathan

**Comment by hongandyan** [comment]
Thanks for the quick help!
Indeed it's a row vector causing the issue.
After chanigng to column, it works like a charm.
thanks again for your effort on this package.
Hong

**Comment by jonathanlilly** [comment]
Great!  Glad that worked!
