### ISSUE TITLE
topoplot can fail without arguments

### ISSUE THREAD

**Issue by selipot** [jonathanlilly/jLab#4]
Sometimes, If I have a plot with x limits beyonds 0 and 360, a call to topoplot fails. Here is an example:

> > figure;xlim([-1 361])
> > topoplot
> > Error using  + 
> > Matrix dimensions must agree.

Error in patchcontourf (line 78)
z1=zeros(size(z,1)+2,size(z,2)+2)+minmin(z);

Error in topoplot (line 205)
    h=patchcontourf(lon,lat,topo,-1/2,[1 1 1]*2/3,str);

**Comment by jonathanlilly** [comment]
This had to do with topoplot failing when the x-axis exceeds 360 degrees.  This issue has been fixed and will be included in the next release.
