### ISSUE TITLE
cell2col not working as expected

### ISSUE THREAD

**Issue by selipot** [jonathanlilly/jLab#7]
cell2col is not working as I expect:
  cell2col({[1 NaN 2 3]'*(1+1i)}) returns
  1 +                     1i
   Inf +                     0i
   2 +                     2i
   3 +                     3i
   NaN +                   NaNi

whereas I expected

1 +                     1i
Inf +                     Infi
...

that is maybe because

 nan+sqrt(-1)_nan==nan_(1+1i) is 0

but 

 1+sqrt(-1)==1+1i is 1?

**Comment by jonathanlilly** [comment]
This has been addressed, and the corrected version will be included in the next release, along with a test.
